apiVersion: v1
kind: Template
labels: {}
metadata:
  annotations:
    description: "# Karaf Camel Rest SQL"
    iconClass: icon-java
  labels: {}
  name: s2i-quickstart-karaf-camel-rest-sql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      component: ${APP_NAME}
      container: karaf
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${SERVICE_NAME}
  spec:
    clusterIP: None
    deprecatedPublicIPs: []
    ports:
    - port: 9411
      protocol: TCP
      targetPort: 8181
    selector:
      component: ${APP_NAME}
      container: karaf
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      container: karaf
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec: {}
  status:
    dockerImageRepository: ''
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      container: karaf
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    resources: {}
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        - name: MAVEN_ARGS
          value: ${MAVEN_ARGS}
        - name: MAVEN_ARGS_APPEND
          value: ${MAVEN_ARGS_APPEND}
        forcePull: true
        from:
          kind: ImageStreamTag
          name: fis-karaf-openshift:${BUILDER_VERSION}
          namespace: ${IMAGE_STREAM_NAMESPACE}
      type: Source
    triggers:
    - github:
        secret: ${BUILD_SECRET}
      type: GitHub
    - generic:
        secret: ${BUILD_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      component: ${APP_NAME}
      container: karaf
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      component: ${APP_NAME}
      container: karaf
      deploymentconfig: ${APP_NAME}
      group: quickstarts
      project: ${APP_NAME}
      provider: s2i
      version: ${APP_VERSION}
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: ${APP_NAME}
          container: karaf
          deploymentconfig: ${APP_NAME}
          group: quickstarts
          project: ${APP_NAME}
          provider: s2i
          version: ${APP_VERSION}
      spec:
        containers:
        - image: library/${APP_NAME}:latest
          name: ${APP_NAME}
          ports:
          - containerPort: 8181
            name: http
          - containerPort: 8778
            name: jolokia
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - (curl -f 127.0.0.1:8181) >/dev/null 2>&1; test $? != 7
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources: {}
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
  status: {}
parameters:
- description: Application Name
  name: APP_NAME
  value: s2i-quickstart-karaf-camel-rest-sql
- description: Git repository, required
  name: GIT_REPO
  required: true
- description: Git ref to build
  name: GIT_REF
  value: master
- description: Exposed Service name
  name: SERVICE_NAME
  value: s2i-qs-karaf-camel-rest-sql
- description: Builder version
  name: BUILDER_VERSION
  value: '1.0'
- description: Application version
  name: APP_VERSION
  value: 2.2.0.redhat-079
- description: Arguments passed to mvn in the build
  name: MAVEN_ARGS
  value: install -DskipTests -e
- description: Extra arguments passed to mvn, e.g. for multi-module builds
  name: MAVEN_ARGS_APPEND
- description: Maven build directory
  name: ARTIFACT_DIR
- description: Namespace in which the Fuse ImageStreams are installed. These ImageStreams
    are normally installed in the openshift namespace. You should only need to modify
    this if you've installed the ImageStreams in a different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: The secret needed to trigger a build
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: BUILD_SECRET
